### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by stephenpatten** [Ash258/Scoop-Core#108]
Is shovel going to be another version of scoop or at least compatible with it?  I've been grok'n scoop for a few weeks now and like it , can you explain where shovel is and going?

Thank you,
Stephen

**Comment by Ash258** [comment]
More stable, usable version of scoop with focus on scripting usage and user-friendliness. In future it will be diverged I hope, since no one take care of vanilla scoop and I do not want to conflict with luke's preference of avoding powershell's verbosity and mainly with the userbase built around it.

https://github.com/Ash258/Scoop-Core/blob/master/CHANGELOG.md
